

###
GET http://localhost:8080/book

###
GET http://localhost:8080/book/2

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "nomeDoLivro": "Livro de Java Avançado II",
  "autorDoLivro": "Carlos Pijanowski Cartaxo",
  "ano": 2010
}

###
DELETE http://localhost:8080/book/1